name: cli
description: A sample command-line application.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  dart_duckdb:
    path: ../../

dev_dependencies:
  lints: ^4.0.0
  test: ^1.26.3

dependency_overrides:
  test_api: ^0.7.7
